apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: items-list
  name: mongo
  namespace: anil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-list
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: items-list
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: storage  
      volumes:
      - name: storage
        persistentVolumeClaim:
           claimName: mongo-pvc      
status: {}
