apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mongo-pvc
  namespace: anil
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Mi
